#! /usr/bin/env python3

"""Compare various choices of shift for sliders.

usage:

    compare-shifts --repo=REPO [<c>=PATH...]

where each PATH is a *.sliders file with or without shifts, and <c> is
the character with which that file's shift will be presented.

"""

import sys
import os
import io
import re
import argparse
from collections import OrderedDict

sys.path.insert(0, os.path.dirname(sys.argv[0]))

import diff_heuristics
from diff_heuristics import compute_slider
from diff_heuristics import iter_shifts


def main(args):
    parser = argparse.ArgumentParser(
        description='Read a slider shift from a diff'
        )
    parser.add_argument('--repo', type=str, required=True)
    parser.add_argument('--all', '-a')
    parser.add_argument('--any-nonzero', action='store_true')
    parser.add_argument('--verbose', '-v', action='store_true')
    parser.add_argument('--correct', type=str)
    parser.add_argument('columns', nargs='+')

    options = parser.parse_args(args)

    if options.verbose:
        diff_heuristics.verbose = True

    column_names = []

    # A dict {(old, new, prefix, line_number) : {column_name : shift}}:
    all_shifts = OrderedDict()

    slider_intern = {}

    for column in options.columns:
        (column_name, path) = column.split('=', 1)
        column_names.append(column_name)
        if path != '0':
            if not os.path.isfile(path):
                sys.stderr.write('Skipping non-existing file %r\n' % (path,))
                continue
            with open(path) as f:
                for (old, new, prefix, line_number, shifts) in iter_shifts(f):
                    params = (old, new, prefix, line_number)
                    params = slider_intern.setdefault(params, params)
                    all_shifts.setdefault(params, {})[column_name] = shifts

    for column in options.columns:
        (column_name, path) = column.split('=', 1)
        if path == '0':
            for values in all_shifts.values():
                values[column_name] = [0]

    differences = 0

    for ((old, new, prefix, line_number), values) in all_shifts.items():
        (old_sha1, old_filename) = old.split(':', 1)
        (new_sha1, new_filename) = new.split(':', 1)
        columns = []
        shifts_seen = set()
        correct = None
        for column_name in column_names:
            shifts = values.get(column_name, [])

            if options.correct and column_name == options.correct:
                correct = set(shifts)
                for shift in shifts:
                    columns.append((column_name, shift))
            else:
                for shift in shifts:
                    columns.append((column_name, shift))
                    shifts_seen.add(shift)

        if (
                options.all
                or options.correct and correct and shifts_seen - correct
                or options.any_nonzero and list(shifts_seen) != [0]
                ):
            slider = compute_slider(
                'corpus/%s.git' % (options.repo,),
                old_sha1, old_filename,
                new_sha1, new_filename,
                prefix, line_number,
                )

            print('%s %s %s %d' % (old, new, prefix, line_number))
            print('# %s' % ('v' * 60,))
            slider.show_comparison(columns, line_prefix='# ')
            print('# %s' % ('^' * 60,))
            print('#')

            differences += 1

    if options.correct:
        print(
            'Number of incorrect shifts: %d' % (differences,),
            file=sys.stderr
            )


if __name__ == '__main__':
    main(sys.argv[1:])
