#! /bin/sh

GIT_DIFF="git -c diff.algorithm=myers diff -U10"
#GIT_DIFF="bgit -c diff.algorithm=myers diff --compaction-heuristic -U10"

git rev-list --no-merges HEAD |
	while read c
	do
		echo $c
		$GIT_DIFF $c^..$c </dev/null |
			~/self/proj/git/git/improve-diff 2>&1
	done
