#! /usr/bin/env python3

"""Choose the 'best' shift for a particular slider.

usage:

    improve-slider --repo=REPO [--verbose]

To stdin should be written one or more sliders to be processed, in the
following format:

    <old-sha1>:<old-filename> <new-sha1>:<new-filename> [-/+] <line-number> [<shift>...]

where

* <sha1>:<filename> names a blob to be diffed.

* [-/+] is '-' if lines are being deleted, '+' if lines are being
  added.

* <line-number> is the line number of the first line being
  added/deleted, when the slider is shifted to its canonical position.
  The line number is relative to the old blob if lines are being
  deleted and relative to the new blob if lines are being added.

* <shift> can be integers. These are ignored.

Write the results to stdout in the same format as the input, where
<shift> is the preferred shift.

"""

import sys
import os
import io
import re
import argparse

sys.path.insert(0, os.path.dirname(sys.argv[0]))

import diff_heuristics
from diff_heuristics import SliderName
from diff_heuristics import SplitScorer
from diff_heuristics import SplitScorer2


def main(args):
    parser = argparse.ArgumentParser(
        description='Read a slider shift from a diff'
        )
    parser.add_argument('--repo', type=str, required=True)
    parser.add_argument('--verbose', '-v', action='store_true')
    SplitScorer2.add_arguments(parser)

    options = parser.parse_args(args)

    if options.verbose:
        diff_heuristics.verbose = True

    scorer = SplitScorer2.from_options(options)

    for (slidername, shifts) in SliderName.read(sys.stdin):
        (old_sha1, old_filename) = slidername.old.split(':', 1)
        (new_sha1, new_filename) = slidername.new.split(':', 1)

        try:
            slider = slidername.compute_slider(
                'corpus/%s.git' % (options.repo,)
                )
        except diff_heuristics.ParsingError as e:
            sys.stderr.write(
                'Error parsing slider %s: %s\n' % (slidername, e,)
                )
        else:
            slidername.write(sys.stdout, slider.find_best_shift(scorer))


if __name__ == '__main__':
    main(sys.argv[1:])
