#! /usr/bin/env python3

import sys
import os
import io
import argparse

sys.path.insert(0, os.path.dirname(sys.argv[0]))

import diff_heuristics
from diff_heuristics import compute_diff
from diff_heuristics import iter_shifts
from diff_heuristics import find_slider


def main(args):
    parser = argparse.ArgumentParser(
        description='Improve sliders read from stdin, showing scores'
        )
    parser.add_argument('--repo', type=str, required=True)
    parser.add_argument('--verbose', '-v', action='store_true')

    options = parser.parse_args(args)

    if options.verbose:
        diff_heuristics.verbose = True

    for (old, new, prefix, line_number, shifts) in iter_shifts(sys.stdin):
        (old_sha1, old_filename) = old.split(':', 1)
        (new_sha1, new_filename) = new.split(':', 1)

        lines = compute_diff(options.repo, old, new)
        slider = find_slider(lines, old_filename, new_filename, prefix, line_number)

        print(
            '%s:%s %s:%s %s %d' % (
                old_sha1, old_filename,
                new_sha1, new_filename,
                slider.prefix, slider.line_number,
                )
            )
        slider.show()


if __name__ == '__main__':
    main(sys.argv[1:])
