#! /usr/bin/env python3

import sys
import os
import io
import argparse

sys.path.insert(0, os.path.dirname(sys.argv[0]))

import diff_heuristics
from diff_heuristics import SliderName
from diff_heuristics import DefaultSplitScorer as SplitScorer


def main(args):
    parser = argparse.ArgumentParser(
        description='Improve sliders read from stdin, showing scores'
        )
    parser.add_argument('--repo', type=str, required=True)
    parser.add_argument('--verbose', '-v', action='store_true')
    SplitScorer.add_arguments(parser)

    options = parser.parse_args(args)

    if options.verbose:
        diff_heuristics.verbose = True

    scorer = SplitScorer.from_options(options)

    for (slidername, shifts) in SliderName.read(sys.stdin):
        slider = slidername.compute_slider('corpus/%s.git' % (options.repo,))
        print(str(slidername))
        slider.show(scorer)


if __name__ == '__main__':
    main(sys.argv[1:])
